trigger:
  batch: true
  branches:
    include:
      - '*'

pool:
  vmImage: windows-latest
  
variables:
- name: buildConfiguration
  value: 'Release'

stages:
  - stage: Build
    displayName: Dotnet Build 
    jobs:
      - job: Build
        steps:
        - task: UseDotNet@2
          displayName: Install Dotnet
          inputs:
            packageType: sdk
            version: '7.x'
            includePreviewVersions: true
            installationPath: '$(Agent.ToolsDirectory)/dotnet'
            performMultiLevelLookup: true

        - task: DotNetCoreCLI@2
          displayName: 'dotnet restore'
          inputs:
            command: 'restore'
            projects: '**/*.csproj'
        
        - task: DotNetCoreCLI@2
          displayName: 'dotnet build'
          inputs:
            command: 'build'
            projects: '**/*.csproj'
            arguments: '--no-restore --configuration $(buildConfiguration)'
        
        - task: DotNetCoreCLI@2
          displayName: 'dotnet test'
          inputs:
            command: 'test'
            projects: '**/*Tests/*.csproj'
            arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura'
            publishTestResults: true

        - task: PublishCodeCoverageResults@1
          displayName: 'Publish code coverage report'
          inputs:
            codeCoverageTool: 'Cobertura'
            summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'